namespace EtimadScraper.Entities;

/// <summary>
/// SQL Server entity for tenders fetched from the Etimad JSON API
/// (AllSupplierTendersForVisitorAsync endpoint).
///
/// Stored in the "SupplierTenders" table.
/// The unique key is <see cref="TenderId"/> from the API; duplicates are
/// prevented via a unique index and the upsert logic in
/// <see cref="Services.SupplierTenderSyncService"/>.
/// </summary>
public class SupplierTenderEntity
{
    /// <summary>Surrogate primary key (auto-generated by SQL Server).</summary>
    public int Id { get; set; }

    // ------------------------------------------------------------------
    // Business key – used for upsert deduplication
    // ------------------------------------------------------------------

    /// <summary>
    /// Numeric tender ID from the Etimad API.
    /// Has a unique index; used as the stable deduplication key.
    /// </summary>
    public int TenderId { get; set; }

    // ------------------------------------------------------------------
    // Core fields
    // ------------------------------------------------------------------

    public string? ReferenceNumber { get; set; }
    public string? TenderName { get; set; }
    public string? TenderNumber { get; set; }
    public string? BranchName { get; set; }
    public string? AgencyName { get; set; }
    public string? TenderIdString { get; set; }

    // ------------------------------------------------------------------
    // Status / type
    // ------------------------------------------------------------------

    public int? TenderStatusId { get; set; }
    public int? TenderTypeId { get; set; }
    public string? TenderTypeName { get; set; }

    // ------------------------------------------------------------------
    // Dates
    // ------------------------------------------------------------------

    public string? LastEnqueriesDate { get; set; }
    public string? LastOfferPresentationDate { get; set; }
    public string? OffersOpeningDate { get; set; }
    public string? SubmitionDate { get; set; }

    // ------------------------------------------------------------------
    // Financial
    // ------------------------------------------------------------------

    public int? TenderActivityId { get; set; }
    public decimal? FinancialFees { get; set; }
    public decimal? InvitationCost { get; set; }
    public decimal? BuyingCost { get; set; }

    // ------------------------------------------------------------------
    // Remaining time (snapshot at last sync)
    // ------------------------------------------------------------------

    public int? RemainingDays { get; set; }
    public int? RemainingHours { get; set; }
    public int? RemainingMins { get; set; }

    /// <summary>Server timestamp string returned by the API for this record.</summary>
    public string? CurrentDateTime { get; set; }

    // ------------------------------------------------------------------
    // Audit
    // ------------------------------------------------------------------

    /// <summary>UTC timestamp of the first insert.</summary>
    public DateTime FirstSyncedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp of the most recent update.</summary>
    public DateTime LastSyncedAt { get; set; } = DateTime.UtcNow;
}
