namespace EtimadScraper.Entities;

/// <summary>
/// SQL Server entity for tenders fetched from the Etimad JSON API
/// (AllSupplierTendersForVisitorAsync endpoint).
///
/// Stored in the "SupplierTenders" table.
/// The unique key is <see cref="TenderId"/> from the API; duplicates are
/// prevented via a unique index and the upsert logic in
/// <see cref="Services.SupplierTenderSyncService"/>.
/// </summary>
public class SupplierTenderEntity
{
    /// <summary>Surrogate primary key (auto-generated by SQL Server).</summary>
    public int Id { get; set; }

    // ------------------------------------------------------------------
    // Business key – used for upsert deduplication
    // ------------------------------------------------------------------

    /// <summary>
    /// Numeric tender ID from the Etimad API.
    /// Has a unique index; used as the stable deduplication key.
    /// </summary>
    public int TenderId { get; set; }

    // ------------------------------------------------------------------
    // Core fields
    // ------------------------------------------------------------------

    public string? ReferenceNumber { get; set; }
    public string? TenderName { get; set; }
    public string? TenderNumber { get; set; }
    public string? BranchName { get; set; }
    public string? AgencyName { get; set; }
    public string? TenderIdString { get; set; }

    // ------------------------------------------------------------------
    // Status / type
    // ------------------------------------------------------------------

    public int? TenderStatusId { get; set; }

    /// <summary>Human-readable status label (e.g. "?????").</summary>
    public string? TenderStatusName { get; set; }

    /// <summary>String representation of the tender status ID.</summary>
    public string? TenderStatusIdString { get; set; }

    public int? TenderTypeId { get; set; }
    public string? TenderTypeName { get; set; }

    // ------------------------------------------------------------------
    // Dates
    // ------------------------------------------------------------------

    public string? LastEnqueriesDate { get; set; }
    public string? LastOfferPresentationDate { get; set; }
    public string? OffersOpeningDate { get; set; }
    public string? SubmitionDate { get; set; }

    /// <summary>Enquiry deadline in Hijri calendar format.</summary>
    public string? LastEnqueriesDateHijri { get; set; }

    /// <summary>Offers opening date in Hijri calendar format.</summary>
    public string? OffersOpeningDateHijri { get; set; }

    /// <summary>Offer presentation deadline in Hijri calendar format.</summary>
    public string? LastOfferPresentationDateHijri { get; set; }

    // ------------------------------------------------------------------
    // Financial
    // ------------------------------------------------------------------

    public int? TenderActivityId { get; set; }
    public decimal? FinancialFees { get; set; }
    public decimal? InvitationCost { get; set; }
    public decimal? BuyingCost { get; set; }

    /// <summary>Conditional booklet price (????? ?????? ????????).</summary>
    public decimal? CondetionalBookletPrice { get; set; }

    // ------------------------------------------------------------------
    // Remaining time (snapshot at last sync)
    // ------------------------------------------------------------------

    public int? RemainingDays { get; set; }
    public int? RemainingHours { get; set; }
    public int? RemainingMins { get; set; }

    /// <summary>Server timestamp string returned by the API for this record.</summary>
    public string? CurrentDateTime { get; set; }

    // ------------------------------------------------------------------
    // Invitation / UGRP flags
    // ------------------------------------------------------------------

    /// <summary>Indicates whether the tender has active invitations.</summary>
    public bool? HasInvitations { get; set; }

    /// <summary>Indicates whether the tender is part of the UGRP programme.</summary>
    public bool? IsUGRP { get; set; }

    /// <summary>URL for the UGRP RFX details page.</summary>
    public string? UgrpRfxUrl { get; set; }

    /// <summary>URL for submitting a UGRP RFX response.</summary>
    public string? UgrpRFXResponseURL { get; set; }

    // ------------------------------------------------------------------
    // AI Evaluation
    // ------------------------------------------------------------------

    /// <summary>AI-assigned matching score (0–100) against the company profile.</summary>
    public decimal? MatchingScore { get; set; }

    /// <summary>Short AI-generated explanation of why the score was assigned.</summary>
    public string? MatchingReason { get; set; }

    /// <summary>
    /// Whether this tender has been evaluated by the AI scoring service.
    /// <see langword="null"/> or <see langword="false"/> means not yet evaluated.
    /// </summary>
    public bool? Evaluated { get; set; }

    // ------------------------------------------------------------------
    // Audit
    // ------------------------------------------------------------------

    /// <summary>UTC timestamp of the first insert.</summary>
    public DateTime FirstSyncedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp of the most recent update.</summary>
    public DateTime LastSyncedAt { get; set; } = DateTime.UtcNow;
}
