namespace EtimadScraper.Entities;

/// <summary>
/// SQL Server entity representing a persisted tender record.
/// TenderNumber is the stable business key used to prevent duplicates.
/// </summary>
public class TenderEntity
{
    /// <summary>Surrogate primary key (auto-generated by SQL Server)</summary>
    public int Id { get; set; }

    /// <summary>
    /// Unique business key from Etimad (e.g. "T-2024-00123").
    /// Has a unique index in the database – used for upsert logic.
    /// Falls back to DetailsUrl when TenderNumber is empty.
    /// </summary>
    public string TenderNumber { get; set; } = string.Empty;

    public string Title { get; set; } = string.Empty;
    public string Organization { get; set; } = string.Empty;
    public string PublishDate { get; set; } = string.Empty;
    public string ClosingDate { get; set; } = string.Empty;

    /// <summary>Full URL to the tender details page – also usable as a fallback unique key.</summary>
    public string DetailsUrl { get; set; } = string.Empty;

    public string Category { get; set; } = string.Empty;
    public string Department { get; set; } = string.Empty;
    public string Status { get; set; } = string.Empty;
    public string AdditionalInfo { get; set; } = string.Empty;

    /// <summary>UTC timestamp of the first successful scrape that created this row.</summary>
    public DateTime FirstScrapedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp of the most-recent scrape that touched this row.</summary>
    public DateTime LastScrapedAt { get; set; } = DateTime.UtcNow;
}
